#!/bin/sh

set -e
set -u
set -x
set -o pipefail

BASE_URL=http://[fd65:7b9c:569:680:98eb:c508:ea6b:b0b2]:2379/v2/keys

while true; do
  rm -rf /tmp/network-units/
  mkdir /tmp/network-units/
  source /etc/ip-allocator-opts/dnsmasq-opts.env
  for key in `curl ${BASE_URL}/kubermesh.github.io/ipv4-overlay/ | jq -r '.node.nodes | .[].key'`; do
    IP_ADDRESSES=`curl ${BASE_URL}${key} | jq -r .node.value`
    INTERFACE_NAME=v4t`echo $IP_ADDRESSES | awk '{print $1}' | tr . '\n' | awk '{s = s*256 + $1} END{print s}'`
    NETDEV_FILE=/tmp/network-units/${INTERFACE_NAME}.netdev
    NETWORK_FILE=/tmp/network-units/${INTERFACE_NAME}.network
    REMOTE_IP=${key##*/}
    if [ "${REMOTE_IP}" != "${VIP_IP}" ]; then
      cat >${NETDEV_FILE} <<EOF
[NetDev]
Name=${INTERFACE_NAME}
Kind=ip6tnl

[Tunnel]
Local=${VIP_IP}
Remote=${REMOTE_IP}
Mode=ipip6
EOF
      cat >${NETWORK_FILE} <<EOF
[Match]
Name=${INTERFACE_NAME}
[Network]
IPForward=ipv4
EOF
      for ip in ${IP_ADDRESSES}; do
        echo '[Route]' >>${NETWORK_FILE}
        echo "Destination=${ip}" >>${NETWORK_FILE}
      done
    fi
  done
  DIFFERENCES=false
  for f in `find /tmp/network-units/ -type f`; do
    if ! diff -rq $f /target/${f##*/}; then
      # File is different
      DIFFERENCES=true
      cp $f /target/${f##*/}
    fi
  done
  if [ "${DIFFERENCES}" = true ]; then
    nsenter --target=1 --mount --wd=. -- /usr/bin/systemctl restart systemd-networkd
  fi
  sleep 10
done
